notifications:
  email: false
language: c
sudo: required
os: linux
cache: apt

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -qq update
  - sudo apt-get install -y curl git gperf flex bison libncurses5-dev libcurl3 libcurl3-gnutls libcurl4-gnutls-dev

install:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
  - tar -xvf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
  - export PATH=$PWD/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH

  - wget http://ymorin.is-a-geek.org/download/kconfig-frontends/kconfig-frontends-4.11.0.1.tar.xz
  - tar -xvf kconfig-frontends-4.11.0.1.tar.xz
  - pushd kconfig-frontends-4.11.0.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  - cd .. && git clone --depth=50 --branch=master https://bitbucket.org/nuttx/apps.git apps && cd -

script:
  - tools/ci/build.sh ${TRAVIS_NUTTX_CONFIG}

env:
  matrix:
    - TRAVIS_NUTTX_CONFIG=clicker2-stm32/xbee-6lowpan
    - TRAVIS_NUTTX_CONFIG=stm3240g-eval/fb
    - TRAVIS_NUTTX_CONFIG=stm32f429i-disco/nsh
    - TRAVIS_NUTTX_CONFIG=stm32f769i-disco/nsh-ethernet

  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "tQJioxUeMpLbIfgaZ/if8cuGx1fgNX5D+/W8tg4aChdXHL1YQdQdRdjH/d3SFGQXnPP3ZCj1ikzGJnYmFJ/+hh0pCEWBlp9PF6wfA76fM+k16J6yi/fzKLehvlhKhlU9VNim9/PuBTd2kEs4SKfb3qHzl9yqiwHyXibiyDGdtmV+Q2syjRlnknxR2M6JTqU4YS+a4f8kiMulOnQ/lJcocOFSq1gWzXS0yaSYPOY8WZJfoGumbsGXodetNxsj0sBOjVtCnyD3FommJf28bzU+8+rnydTBVLCUQKaR6l4UmJrz5whv9sTJ3jHVyK/1kF6dnrqVDI+yiaYKwIezwMS5PYLoFkLGCJogMTUGHSyVbCP0fnO1wkwutxeAQG5zrHvsoXFccg9E0O0rZsofZw170g38NxYjz5qVRfkha5hrSkr8PwAHyVkhcIqpXYRw1y6KNZp4d94ejN6ZO7cOBR0FN8W51OWeW0cluhqd2H/LowoZIpNbdUlCVrver3PyCuLZv+fZOoKXNMGAMKRHgND3U6EoWGZX+SxPMIObQmrQWZgi5GwSmTKHxiZj/bzL7ULYbPHgK72vPgznxOHdwPQPjbItVp97evkvEMReomVwtANr/GnO1bOxqvAiwcZIeqMnWy7ehiZMrhdrDQUiHqNibkwSuh2mfRDuskjpLwVnZ0Q="

matrix:
 fast_finish: true
 include:
   - env: COVERITY=1
 allow_failures:
   - env: COVERITY=1
