notifications:
  email: false

language: c

cache: apt

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "M9n5fclEZ8jvyaDYft4qTaJyJH5NwFETHAVhEHHPBD/1e5OjNNV9NaXUJgnZL0Pp+uDtS6SLQMxCkZYlUjgxidyUfTqJR/kTO85jVZQK+pv3wS+v9bnp4HIsUftJQ0uWWZoRaQJyjWPlQboTxOVyDNL57vvibij3ZnxhNYlKjZ12l/ASmQO4FSwSt2gIqHZ4Pz0Q8KtHxbObzPuUWyc9rCgziCcJpqiQI5svPPz61t8FlCKUHGQaKbAJXuiS07KaI0Tsd0BcD7JQzYFsaFBNZelVJa3SvThF25hSscxs1UhynzauNdMKwMzhMzI0y6F7pU/nFXAtJuGgbiuMgi35JWIiBtDvcHyEwdwXi8HvDWkg3uchVuHWiZNhaU7TVTb/u0epH14yux1Mp5pfmImVD7hPuzeMBx8YnPbq4sqYvzsU8gYnGuWXdgHEsZYPt1EcVf7mr5qnV78eqUZsP2sR8dvhHS70xQTqt9B3xcIQ3bfqetHlpFxLQjUPwOITqSryg5q3HilJCPxv2C3rygbnKgM2FFVRVDTmZ38v4VXM7BzklWrPVRlZshoMpYsDT+tqJCXoZ3bqEzkDk+0DkBPHnhJ88Wui5YgY4VE1fO5vJBVSbhqIJFYSonjCM3m4vFcnAtAAYR0F8XhBXtshLXUHYBS57UuVG0Jl0umeWGymVe4="

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi

  coverity_scan:
    project:
      name: "bherrera/NuttX"
      description: "Build submitted via Travis CI"
    notification_email: bruherrera@gmail.com
    build_command_prepend: "cd tools; ./configure.sh stm32f429i-disco/nsh; cd ..;"
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - arm-none-eabi-gcc --version

  # Download repo dependency at top level dir
  - cd ..
  - git clone https://bitbucket.org/nuttx/apps.git apps
  - cd -

before_script:
  # Build stm32f429i-disco/nsh config
  - cd tools
  - ./configure.sh stm32f429i-disco/nsh
  - cd ..

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ] ; then
      make V=1;
    fi

