notifications:
  email: false

language: c
sudo: required
os: linux
cache: apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git gperf flex bison libncurses5-dev

  # Download repo dependency at top level dir
  - cd ..
  - git clone https://bitbucket.org/nuttx/apps.git apps
  - cd -

install: 
  # GCC ARM NONE EABI
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 
  - tar -xvf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 
  - export PATH=gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH

  # kconfig-frontends
  - wget http://ymorin.is-a-geek.org/download/kconfig-frontends/kconfig-frontends-4.11.0.1.tar.xz
  - tar -xvf kconfig-frontends-4.11.0.1.tar.xz
  - pushd kconfig-frontends-4.11.0.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  # Build stm32f429i-disco/nsh config
  - make distclean
  - cd tools
  - ./configure.sh stm32f429i-disco/nsh
  - cd ..

script:
  - git submodule update --quiet --init --recursive
  - make

