notifications:
  email: false

language: c
sudo: required
os: linux
cache: apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git gperf flex bison libncurses5-dev

  # Download repo dependency at top level dir
  - cd ..
  - git clone https://bitbucket.org/nuttx/apps.git apps
  - cd -

install:
  - wget http://ymorin.is-a-geek.org/download/kconfig-frontends/kconfig-frontends-4.11.0.1.tar.xz
  - tar -xzvf kconfig-frontends-4.11.0.1.tar.xz
  - pushd kconfig-frontends-4.11.0.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  # Build stm32f429i-disco/nsh config
  - make distclean
  - cd tools
  - ./configure.sh stm32f429i-disco/nsh
  - cd ..

script:
  - git submodule update --quiet --init --recursive
  - make

